// components/pages/exam/ExamAuthentication.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";

interface ExamAuthenticationProps {
  examId: string;
  school: string;
}

interface ExamDetails {
  id: string;
  title: string;
  subject: string;
  duration: number;
  totalMarks: number;
  instructions: string;
  requiresAuthentication: boolean;
}

const ExamAuthentication: React.FC<ExamAuthenticationProps> = ({
  examId,
  school,
}) => {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  const [exam, setExam] = useState<ExamDetails | null>(null);
  const [formData, setFormData] = useState({
    studentId: "",
    accessCode: "",
  });
  const [errors, setErrors] = useState<{
    studentId?: string;
    accessCode?: string;
  }>({});
  const [isAuthenticating, setIsAuthenticating] = useState(false);

  // Check if user is already logged in
  useEffect(() => {
    const checkAuth = async () => {
      const token = localStorage.getItem("examToken");
      const currentExamId = localStorage.getItem("currentExamId");

      if (token && currentExamId === examId) {
        // User is already authenticated for this exam
        router.push(`/${school}/${examId}`);
        return;
      }

      // Fetch exam details
      try {
        // Simulate API call to get exam details
        const examData: ExamDetails = {
          id: examId,
          title: "Mathematics Final Examination",
          subject: "Mathematics",
          duration: 120,
          totalMarks: 100,
          instructions:
            "This exam consists of multiple choice questions. You have 2 hours to complete it.",
          requiresAuthentication: true,
        };
        setExam(examData);
      } catch (error) {
        console.error("Error fetching exam details:", error);
      } finally {
        setIsLoading(false);
      }
    };

    checkAuth();
  }, [examId, router]);

  const validateForm = () => {
    const newErrors: { studentId?: string; accessCode?: string } = {};

    if (!formData.studentId.trim()) {
      newErrors.studentId = "Student ID is required";
    }

    if (!formData.accessCode.trim()) {
      newErrors.accessCode = "Access code is required";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleStartExam = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setIsAuthenticating(true);

    try {
      // Simulate API call to verify student and access code
      await new Promise((resolve) => setTimeout(resolve, 1500));

      // In real app, you would call your backend to verify credentials
      const isValid = await verifyStudentCredentials(
        formData.studentId,
        formData.accessCode,
        examId
      );

      if (isValid) {
        // Generate exam session token
        const examToken = generateExamToken();

        // Store in localStorage (in real app, use HTTP-only cookies)
        localStorage.setItem("examToken", examToken);
        localStorage.setItem("currentExamId", examId);
        localStorage.setItem("examStartTime", Date.now().toString());

        // Redirect to exam page
        router.push(`/exam/${examId}`);
      } else {
        setErrors({
          accessCode:
            "Invalid student ID or access code. Please check your credentials.",
        });
      }
    } catch (error) {
      setErrors({
        accessCode: "Authentication failed. Please try again.",
      });
    } finally {
      setIsAuthenticating(false);
    }
  };

  const verifyStudentCredentials = async (
    studentId: string,
    accessCode: string,
    examId: string
  ): Promise<boolean> => {
    // Simulate API call to backend
    // In real app, this would verify against your database
    return new Promise((resolve) => {
      setTimeout(() => {
        // Mock validation - in real app, check against database
        resolve(studentId.length > 3 && accessCode.length > 3);
      }, 1000);
    });
  };

  const generateExamToken = (): string => {
    // In real app, this should be generated by the backend
    return `exam_token_${Date.now()}_${Math.random()
      .toString(36)
      .substr(2, 9)}`;
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <i className="fas fa-spinner fa-spin text-4xl text-primary mb-4"></i>
          <p className="text-gray-600">Loading exam details...</p>
        </div>
      </div>
    );
  }

  if (!exam) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <i className="fas fa-exclamation-triangle text-4xl text-red-500 mb-4"></i>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Exam Not Found
          </h2>
          <p className="text-gray-600">
            The requested exam could not be found.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="max-w-md w-full">
        {/* Exam Header */}
        <div className="bg-white rounded-xl shadow-sm p-6 mb-6 text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">
            {exam.title}
          </h1>
          <p className="text-gray-600 mb-4">{exam.subject}</p>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-gray-600">Duration</p>
              <p className="font-semibold">{exam.duration} minutes</p>
            </div>
            <div>
              <p className="text-gray-600">Total Marks</p>
              <p className="font-semibold">{exam.totalMarks}</p>
            </div>
          </div>
        </div>

        {/* Authentication Form */}
        <div className="bg-white rounded-xl shadow-sm p-6">
          <div className="text-center mb-6">
            <div className="w-16 h-16 bg-primary rounded-full flex items-center justify-center mx-auto mb-4">
              <i className="fas fa-lock text-white text-2xl"></i>
            </div>
            <h2 className="text-xl font-bold text-gray-900 mb-2">
              Exam Authentication Required
            </h2>
            <p className="text-gray-600">
              Please enter your credentials to start the exam
            </p>
          </div>

          <form onSubmit={handleStartExam} className="space-y-4">
            <Input
              id="studentId"
              label="Student ID"
              placeholder="Enter your student ID"
              value={formData.studentId}
              onChange={(e) =>
                setFormData({ ...formData, studentId: e.target.value })
              }
              error={errors.studentId}
              touched={true}
              disabled={isAuthenticating}
            />

            <Input
              id="accessCode"
              label="Exam Access Code"
              type="password"
              placeholder="Enter exam access code"
              value={formData.accessCode}
              onChange={(e) =>
                setFormData({ ...formData, accessCode: e.target.value })
              }
              error={errors.accessCode}
              touched={true}
              disabled={isAuthenticating}
            />

            <Button
              type="submit"
              variant="primary"
              className="w-full"
              disabled={isAuthenticating}
            >
              {isAuthenticating ? (
                <>
                  <i className="fas fa-spinner fa-spin mr-2"></i>
                  Verifying...
                </>
              ) : (
                <>
                  <i className="fas fa-play mr-2"></i>
                  Start Exam
                </>
              )}
            </Button>
          </form>

          {/* Security Notice */}
          <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <div className="flex items-start space-x-3">
              <i className="fas fa-shield-alt text-yellow-600 mt-0.5"></i>
              <div>
                <h4 className="font-semibold text-yellow-800 text-sm mb-1">
                  Security Measures
                </h4>
                <ul className="text-xs text-yellow-700 space-y-1">
                  <li>• Tab switching will be monitored</li>
                  <li>• Full-screen mode is required</li>
                  <li>• Webcam monitoring may be active</li>
                  <li>• Time cannot be paused once started</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExamAuthentication;
